### ISSUE TITLE
Crashes  Aliucord at load

### ISSUE THREAD

**Issue by governos** [js6pak/WhoReacted#3]
Loading the plug-in crashes the app and triggers Aliucord to disable it on next start.

Seems to come up starting with version 89.8. Let me know what I can do regarding debugging.

**Comment by js6pak** [comment]
Plugins just were not updated to 89.8 yet, I'll do that soonish

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks

**Comment by js6pak** [comment]
Fixed by 26497ecbe7d287a607d8f41a3545101a01834d4f
